const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),Core=require('./dist/core.js');
const {words,lessons}=vm.runInNewContext(fs.readFileSync(path.join(__dirname,'dist/content.js'),'utf8')+';({words:WORDS,lessons:LESSONS})');
const now=100000,db={version:1,round:0,words:{0:{due:now-1,reps:1},1:{due:now+1,reps:1}},history:[],session:null};
const queue=Core.plan(words,db.words,now);assert.equal(queue[0].id,0);assert.equal(queue[0].kind,'review');assert.equal(queue.filter(x=>x.kind==='new').length,10);assert(!queue.some(x=>x.id===1));
const s=Core.session(words,db,now);s.running=true;Core.advance(s,419999);assert.equal(s.stage,0);Core.advance(s,2001);assert.equal(s.stage,1);assert.equal(s.elapsed[1],2000);s.running=false;Core.advance(s,50000);assert.equal(s.elapsed[1],2000);s.running=true;Core.advance(s,1200000);assert.equal(s.finished,true);assert.equal(s.running,false);assert.equal(s.elapsed.reduce((a,b)=>a+b),1200000);
assert.equal(Core.schedule(null,0,now).due,now+600000);let r=Core.schedule(null,2,now);assert.equal(r.due,now+86400000);r=Core.schedule(r,2,now);assert.equal(r.due,now+3*86400000);assert.equal(Core.schedule(r,1,now).due,now+86400000);
assert.equal(Core.score('SMALL local initiatives!','Small local initiatives.'),100);assert(Core.score('Small local','Small local initiatives')<100);assert.equal(Core.score('','hello'),0);
const restored=JSON.parse(JSON.stringify({...db,session:Core.session(words,db,now)}));restored.session.answers.translation='saved draft';restored.session.running=true;Core.validate(restored);assert.equal(restored.session.running,false);assert.equal(restored.session.answers.translation,'saved draft');assert.throws(()=>Core.validate({version:99}));assert.throws(()=>Core.validate({...restored,session:{...restored.session,stage:99}}));
// Validate local assets and bundled WAV headers; no network dependencies.
const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'dist/manifest.webmanifest'),'utf8'));for(const icon of manifest.icons)assert(fs.existsSync(path.join(__dirname,'dist',icon.src)));for(const lesson of lessons){for(const file of [lesson.audio,lesson.audio.replace('.wav','-sentence.wav')]){const wav=fs.readFileSync(path.join(__dirname,'dist',file));assert.equal(wav.toString('ascii',0,4),'RIFF');assert.equal(wav.toString('ascii',8,12),'WAVE');assert(wav.length>10000);}}
// Service worker runs in an isolated context; verify installation, offline shell, and audio Range.
(async()=>{const handlers={},entries=new Map();const cache={async addAll(paths){for(const name of paths)entries.set(new URL(name,'https://example.test/').href,new Response(fs.readFileSync(path.join(__dirname,'dist',name==='./'?'index.html':name.slice(2)))));},async put(key,val){entries.set(new URL(key,'https://example.test/').href,val);},async match(key){const r=entries.get(new URL(key,'https://example.test/').href);return r?.clone();}};const context={self:{location:{origin:'https://example.test'},addEventListener:(n,f)=>handlers[n]=f,skipWaiting:async()=>{},clients:{claim:async()=>{},matchAll:async()=>[]}},caches:{open:async()=>cache,keys:async()=>['cet6-v1'],delete:async()=>{}},URL,Response,fetch:async()=>{throw Error('offline')}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'dist/sw.js'),'utf8'),context);let install;handlers.install({waitUntil:p=>install=p});await install;assert(await cache.match('./offline-ready'));let result;handlers.fetch({request:{method:'GET',url:'https://example.test/audio/garden.wav',headers:new Headers({range:'bytes=0-99'})},respondWith:p=>result=p});const range=await result;assert.equal(range.status,206);assert.equal((await range.arrayBuffer()).byteLength,100);handlers.fetch({request:{method:'GET',url:'https://example.test/unknown',headers:new Headers(),mode:'navigate'},respondWith:p=>result=p});assert.equal((await result).status,200);console.log('PASS: review priority, 10 new words, timer boundaries/pause, scheduling, dictation, backup, WAV assets, offline cache and audio ranges.');})().catch(e=>{console.error(e);process.exitCode=1;});
