// Fixed source allowlist. No arbitrary proxy URLs or user answers are sent to publishers.
const SOURCES=[
 {id:'gov-news',name:'中国政府网英文版 · 新闻（含新华社稿件）',url:'https://english.www.gov.cn/news/',hosts:['english.www.gov.cn'],format:'html'},
 {id:'gov-policy',name:'中国政府网英文版 · 最新政策',url:'https://english.www.gov.cn/policies/latestreleases/',hosts:['english.www.gov.cn'],format:'html'},
 {id:'people-society',name:'人民网 · 社会（署名以原文为准）',url:'https://society.people.com.cn/',hosts:['people.com.cn'],format:'html'},
 {id:'people-finance',name:'人民网 · 经济（署名以原文为准）',url:'https://finance.people.com.cn/',hosts:['people.com.cn'],format:'html'},
 {id:'who',name:'WHO 最新消息',url:'https://www.who.int/rss-feeds/news-english.xml',hosts:['www.who.int','who.int']},
 {id:'bbc-education',name:'BBC News · Education',url:'https://feeds.bbci.co.uk/news/education/rss.xml',hosts:['bbc.com','bbc.co.uk']},
 {id:'bbc-science',name:'BBC News · Science & Environment',url:'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml',hosts:['bbc.com','bbc.co.uk']},
 {id:'people-education',name:'人民网 · 教育（报纸归属请查看原文）',url:'https://edu.people.com.cn/GB/index.html',hosts:['people.com.cn'],format:'html'},
 {id:'people-scitech',name:'人民网 · 科技（报纸归属请查看原文）',url:'https://scitech.people.com.cn/',hosts:['people.com.cn'],format:'html'},
 {id:'people-culture',name:'人民网 · 文化（报纸归属请查看原文）',url:'https://culture.people.com.cn/GB/index.html',hosts:['people.com.cn'],format:'html'}
];
const entities=s=>s.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Math.min(Number(n),0x10ffff)));
function plain(s){return entities(String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]*>/g,' ')).replace(/\s+/g,' ').trim();}
function validLink(link,source){try{const u=new URL(link);return u.protocol==='https:'&&source.hosts.some(h=>u.hostname===h||u.hostname.endsWith('.'+h));}catch(e){return false;}}
function parse(xml,source){const blocks=xml.match(/<item\b[^>]*>[\s\S]*?<\/item>/gi)||[];return blocks.map(block=>{const read=name=>plain((block.match(new RegExp('<'+name+'\\b[^>]*>([\\s\\S]*?)<\\/'+name+'>','i'))||[])[1]);const title=read('title'),link=read('link'),published=read('pubDate');return validLink(link,source)&&title?{id:source.id+'-'+link,title,url:link,publisher:source.name,published:!Number.isNaN(Date.parse(published))?new Date(published).toISOString():null,kind:'来源标题',note:'原文新闻线索；不是六级真题，也不是已审核的翻译练习'}:null;}).filter(Boolean).slice(0,30);}
function parseHTML(html,source){return [...html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)].map(m=>{let url;try{url=new URL(m[1],source.url).href;}catch(e){return null;}const title=plain(m[2]),date=url.match(/\/n[12]\/(\d{4})\/(\d{2})(\d{2})\//)||url.match(/\/(\d{4})(\d{2})\/(\d{2})\//);if(!validLink(url,source)||!date||title.length<8||title.length>150)return null;return {id:source.id+'-'+url,title,url,publisher:source.name,published:new Date(date[1]+'-'+date[2]+'-'+date[3]+'T00:00:00+08:00').toISOString(),kind:'来源标题',note:'日期来自文章路径；人民日报署名需在原文确认'};}).filter(Boolean).filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i).slice(0,80);}
let cache=null,lastAttempt=0,inflight=null;
async function getNews(force=false){if(inflight)return inflight;if(!force&&cache&&Date.now()-lastAttempt<300000)return {...cache,status:'cached-server'};lastAttempt=Date.now();inflight=(async()=>{const results=await Promise.allSettled(SOURCES.map(async source=>{const res=await fetch(source.url,{signal:AbortSignal.timeout(8000),headers:{'User-Agent':'CET6-Study/3.0'}});if(!res.ok)throw Error('HTTP '+res.status);if(Number(res.headers.get('content-length')||0)>2000000)throw Error('来源过大');const text=await res.text();if(text.length>2000000)throw Error('来源过大');const parsed=source.format==='html'?parseHTML(text,source):parse(text,source);if(!parsed.length)throw Error('没有可用条目');return parsed;}));const items=[],errors=[];results.forEach((r,i)=>{if(r.status==='fulfilled')items.push(...r.value);else errors.push(SOURCES[i].name+': '+r.reason.message);});if(items.length){cache={status:'live',fetchedAt:new Date().toISOString(),items,errors};return cache;}return cache?{...cache,status:'stale',errors}:{status:'unavailable',fetchedAt:null,items:[],errors};})().finally(()=>inflight=null);return inflight;}
module.exports={getNews,parse,parseHTML,SOURCES};
