const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{week,mailConfig,render,run}=require('./weekly-mail.cjs');
(async()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'cet6-weekly-'));try{
 assert.equal(week(Date.parse('2026-10-11T12:00:00Z')),'2026-10-05');assert.equal(week(Date.parse('2026-10-11T16:00:00Z')),'2026-10-12');assert.throws(()=>mailConfig({}));assert.throws(()=>mailConfig({EMAIL_ADDRESS:'test@icloud.com\r\nBcc: victim@example.test',ICLOUD_APP_PASSWORD:'fixture'}));
 const now=Date.parse('2026-10-09T02:00:00Z'),env={EMAIL_ADDRESS:'weekly-test@icloud.com',ICLOUD_APP_PASSWORD:'fixture-password'},events=[],messages=[];
 const options={now,env,stateDirectory:path.join(temp,'state'),outputDirectory:path.join(temp,'out'),news:async()=>{events.push('news');return {items:[{title:'University learning and education',url:'https://www.bbc.com/news/example',publisher:'BBC',published:'2026-10-08T00:00:00Z'}],errors:[]};},generation:async()=>{events.push('AI');return {state:'not-configured'};},transportFactory:settings=>{assert.equal(settings.requireTLS,true);assert.equal(settings.tls.rejectUnauthorized,true);assert.equal(settings.host,'smtp.mail.me.com');assert.equal(settings.port,587);return {verify:async()=>events.push('verify'),sendMail:async message=>{events.push('send');messages.push(message);return {accepted:[env.EMAIL_ADDRESS]};},close(){}};}};
 await assert.rejects(()=>run({...options,env:{}}));assert.equal(events.length,0);const result=await run(options);assert.equal(result.state,'sent');assert.equal(result.materials,5);assert.equal(events[0],'verify');assert.equal(messages[0].to,env.EMAIL_ADDRESS);assert(messages[0].text.includes('已编辑背景专题复习'));assert(messages[0].html.includes('未经人工核验'));assert.equal(messages[0].disableUrlAccess,true);assert.equal(messages[0].attachments.length,1);const after=events.length;assert.equal((await run(options)).state,'already-sent');assert.equal(events.length,after);
 let collected=false;await assert.rejects(()=>run({...options,stateDirectory:path.join(temp,'auth-failure'),news:async()=>{collected=true;},transportFactory:()=>({verify:async()=>{throw Error('bad password');},close(){}})}));assert.equal(collected,false);
 let sent=0;const uncertain={...options,stateDirectory:path.join(temp,'uncertain'),transportFactory:()=>({verify:async()=>{},sendMail:async()=>{sent++;throw Error('connection lost');},close(){}})};await assert.rejects(()=>run(uncertain),/结果不确定/);await assert.rejects(()=>run(uncertain),/结果不确定/);assert.equal(sent,1);
 const report=JSON.parse(fs.readFileSync(path.join(temp,'state','2026-10-05-balanced-v2','report.json'),'utf8'));report.materials[0].material.title='<script>alert(1)</script>';report.materials[0].material.sourceUrl='javascript:alert(1)';const safe=render(report);assert(!safe.html.includes('<script>'));assert(!safe.html.includes('href="javascript:'));assert(safe.html.includes('&lt;script&gt;'));
 const retired=fs.readFileSync('.github/workflows/daily-pages.yml','utf8'),workflow=fs.readFileSync('.github/workflows/weekly-mail.yml','utf8');assert(!retired.includes('schedule:'));assert(!retired.includes('secrets.'));assert(!retired.includes('deploy-pages'));assert(workflow.includes("'0 12 * * 0'"));assert(!workflow.includes('TENCENT'));assert(!workflow.includes('deploy-pages'));assert(!JSON.stringify(report).includes(env.ICLOUD_APP_PASSWORD));
 console.log('PASS: weekly timezone, retired website workflow, credential/SMTP checks before AI, explicit fallback labels, safe HTML, one email per retained week, uncertain delivery stops; no real email or paid calls.');
 }finally{const target=path.resolve(temp),parent=path.resolve(os.tmpdir());if(target.startsWith(parent+path.sep))fs.rmSync(target,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
