const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {getNews}=require('./news.cjs'),{select}=require('./curation.cjs'),{generate,validate,hash}=require('./generate-daily.cjs');
const esc=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function week(now){const bj=new Date(now+8*3600000);bj.setUTCHours(0,0,0,0);bj.setUTCDate(bj.getUTCDate()-((bj.getUTCDay()+6)%7));return bj.toISOString().slice(0,10);}
function mailConfig(env){const address=env.EMAIL_ADDRESS?.trim(),password=env.ICLOUD_APP_PASSWORD;if(!address||! /^[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+@icloud\.com$/i.test(address)||!password||/[\r\n]/.test(password))throw Error('请先配置EMAIL_ADDRESS与ICLOUD_APP_PASSWORD两个GitHub Secrets');return {address,password};}
function sourceLink(url){try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}}
function render(report){
 const lines=['CET-6 翻译与写作周报','周次：'+report.week,'仅作学习练习；AI新编内容经自动复核，未经人工核验，不是真题或预测。',''];
 let html='<main style="max-width:760px;margin:auto;font-family:Arial,sans-serif;line-height:1.8"><h1>CET-6 翻译与写作周报</h1><p>周次：'+esc(report.week)+'</p><p>仅作学习练习；AI新编内容经自动复核，未经人工核验，不是真题或预测。</p>';
 for(const [i,item] of report.materials.entries()){const m=item.material;const url=sourceLink(m.sourceUrl);lines.push((i+1)+'. '+m.title,'主题：'+m.theme,'性质：'+item.label,'来源：'+m.publisher+' '+url,'来源日期：'+m.sourcePublished,'【段落翻译练习】',m.paragraph||m.chinese,'【参考译文】',m.paragraphTranslation||m.translation,'【写作任务】',m.prompt,'【短段范例】',m.sample,'【可迁移句式】',m.pattern,'【词汇搭配】',(m.keywords||[]).join(' / '),'【自检】',(m.checks||[]).join('；'),'');html+='<section><h2>'+esc((i+1)+'. '+m.title)+'</h2><p>'+esc(m.theme+' · '+item.label)+'</p><p>来源：'+esc(m.publisher)+(url?' · <a href="'+esc(url)+'">原文</a>':'')+' · '+esc(m.sourcePublished)+'</p>';for(const [title,value]of [['段落翻译练习',m.paragraph||m.chinese],['参考译文',m.paragraphTranslation||m.translation],['写作任务',m.prompt],['短段范例',m.sample],['可迁移句式',m.pattern],['词汇搭配',(m.keywords||[]).join(' / ')],['自检',(m.checks||[]).join('；')]])html+='<h3>'+title+'</h3><p style="white-space:pre-wrap">'+esc(value)+'</p>';html+='</section>';}
 lines.push('【本周新闻线索】');html+='<h2>本周新闻线索</h2>';if(!report.candidates.length){lines.push('本周未取得符合筛选条件的新闻，以上为明确标注的库存素材复习。');html+='<p>本周未取得符合筛选条件的新闻，以上为库存素材复习。</p>';}
 for(const n of report.candidates){const url=sourceLink(n.url);lines.push(n.title+' | '+n.publisher+' | '+n.published+' | '+url+' | 筛选理由：'+n.reason);html+='<p><a href="'+esc(url)+'">'+esc(n.title)+'</a><br>'+esc(n.publisher+' · '+n.published+' · '+n.reason)+'</p>';}
 if(report.warnings.length){lines.push('【采集与生成说明】',...report.warnings);html+='<h2>采集与生成说明</h2><p>'+report.warnings.map(esc).join('<br>')+'</p>';}
 html+='<p>建议每周完成3组翻译和写作练习，比较参考表达，并记录可迁移句式。</p></main>';return {text:lines.join('\n'),html};
}
async function run({env=process.env,now=Date.now(),stateDirectory=path.join(__dirname,'weekly-state'),outputDirectory=path.join(__dirname,'weekly-output'),news=getNews,generation=generate,transportFactory}={}){
 const cfg=mailConfig(env);fs.mkdirSync(stateDirectory,{recursive:true});const id=week(now),folder=path.join(stateDirectory,id);fs.mkdirSync(folder,{recursive:true});const deliveryFile=path.join(folder,'delivery.json');let delivery=null;try{delivery=JSON.parse(fs.readFileSync(deliveryFile,'utf8'));}catch{}
 if(delivery?.state==='sent')return {state:'already-sent',week:id};if(delivery?.state==='sending'||delivery?.state==='uncertain')throw Error('上次投递结果不确定；为避免重复邮件，本周不自动重发');
 const create=transportFactory||((options)=>require('./.weekly-runtime/node_modules/nodemailer').createTransport(options));const smtp=create({host:'smtp.mail.me.com',port:587,secure:false,requireTLS:true,tls:{minVersion:'TLSv1.2',rejectUnauthorized:true},auth:{user:cfg.address,pass:cfg.password},connectionTimeout:20000,greetingTimeout:20000,socketTimeout:45000,logger:false,debug:false});
 try{
  // Validate SMTP before spending any AI tokens or doing a news refresh.
  await smtp.verify();let report;try{report=JSON.parse(fs.readFileSync(path.join(folder,'report.json'),'utf8'));}catch{}
  if(!report){report={week:id,createdAt:new Date(now).toISOString(),candidates:[],materials:[],warnings:[]};let raw;try{raw=await news(true);}catch{raw={items:[],errors:['新闻采集失败']};}report.warnings.push(...(raw.errors||[]).map(x=>String(x).slice(0,180)));report.candidates=select(raw.items||[],now);
   const topics=[];for(const n of report.candidates)if(!topics.some(t=>t.themeId===n.themeId)&&topics.length<3)topics.push(n);
   const day=new Date(now+8*3600000).toISOString().slice(0,10);for(const [i,n]of topics.entries()){const dir=path.join(folder,'topic-'+i);try{const result=await generation({candidates:[n],day,stateDirectory:dir,reviewDirectory:path.join(folder,'manual-reviews'),controlFile:path.join(folder,'no-extra-retry.json'),env:{...env,AI_AUTO_PUBLISH:'false'}});if(result.state==='awaiting-review'){const draft=JSON.parse(fs.readFileSync(path.join(dir,'generation',day+'.json'),'utf8'));validate(draft.material);if(draft.state!=='ready'||hash(draft.material)!==draft.contentHash)throw Error('草稿校验失败');report.materials.push({label:'本周新闻新编 · AI自动复核通过，未人工核验',material:draft.material});}else report.warnings.push(n.theme+'：未取得合格新编素材（'+result.state+'）');}catch{report.warnings.push(n.theme+'：生成未完成，保留库存素材');}}
   const seed=JSON.parse(fs.readFileSync(path.join(__dirname,'dist/daily-feed.json'),'utf8'));const offset=Math.floor(Date.parse(id)/604800000)%seed.materials.length;for(let j=0;report.materials.length<3&&j<seed.materials.length;j++){const m=seed.materials[(offset+j)%seed.materials.length];report.materials.push({label:'已有素材轮换复习 · 非本周新闻新编',material:m});}
   fs.writeFileSync(path.join(folder,'report.json'),JSON.stringify(report));
  }
  const body=render(report);fs.mkdirSync(outputDirectory,{recursive:true});fs.writeFileSync(path.join(outputDirectory,'weekly-'+id+'.html'),body.html);fs.writeFileSync(path.join(outputDirectory,'weekly-'+id+'.txt'),body.text);
  fs.writeFileSync(deliveryFile,JSON.stringify({week:id,state:'sending',startedAt:new Date().toISOString()}));let result;
  try{result=await smtp.sendMail({from:cfg.address,to:cfg.address,subject:'CET-6 翻译与写作周报｜'+id,messageId:'<cet6-weekly-'+id+'@icloud.com>',text:body.text,html:body.html,attachments:[{filename:'CET6-weekly-'+id+'.html',content:body.html,contentType:'text/html; charset=utf-8'}],disableFileAccess:true,disableUrlAccess:true});if(!result.accepted?.some(a=>String(a).toLowerCase()===cfg.address.toLowerCase()))throw Error('NotAccepted');}catch{fs.writeFileSync(deliveryFile,JSON.stringify({week:id,state:'uncertain'}));throw Error('邮件投递失败或结果不确定；本周停止自动重发，请查看收件箱后再处理');}
  fs.writeFileSync(deliveryFile,JSON.stringify({week:id,state:'sent',sentAt:new Date().toISOString()}));return {state:'sent',week:id,materials:report.materials.length};
 }finally{smtp.close?.();}
}
module.exports={week,mailConfig,render,run};if(require.main===module)run().then(r=>console.log(JSON.stringify(r))).catch(e=>{console.error(/GitHub Secrets|上次投递|邮件投递/.test(e.message)?e.message:'周报未完成：请检查邮箱授权、网络和生成状态；原始错误未输出以保护凭据。');process.exitCode=1;});
